version: '3'
services:
  db:
    image: postgres:latest
    environment:
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiagos
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data: